# Target ABI should be one of: armeabi, armeabi-v7a, x86
# mips ABI is not supported (no native compiler)
ABI = armeabi-v7a

# Which Android platform to use
ANDROID_PLATFORM = android-14

# Path of the Android NDK
ANDROID_NDK = ${OPAM_PREFIX}/lib/android-ndk

# OCaml sources (will be copied)
OCAML_SRC = ${OPAM_PREFIX}/lib/ocaml-src

# Where the cross-compiler libraries are installed
ANDROID_PREFIX = ${OPAM_PREFIX}/$(HOST_ARCH)

# Where the cross-compiler binaries are installed
ANDROID_BINDIR = ${OPAM_PREFIX}/bin

OPAM_PREFIX := $(shell opam config var prefix)
