
# Path of the Android NDK
ANDROID_NDK = /home/jerome/.opam/4.00.1/lib/android-ndk-linux

# OCaml sources (will be copied)
OCAML_SRC = /home/jerome/.opam/4.00.1/lib/ocaml-src

# Where the cross-compiler libraries are installed
ANDROID_PREFIX = $(shell pwd)/ocaml-android

# Where the cross-compiler binaries are installed
ANDROID_BINDIR = /home/jerome/bin
